# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_goodstypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='订单号')),
                ('status', models.IntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '完成')])),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='生成的时间')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(verbose_name='商品数量')),
                ('price', models.FloatField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Order')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('user', 'is_default')]),
        ),
        migrations.AlterIndexTogether(
            name='address',
            index_together=set([('user', 'is_default')]),
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
