# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20190307_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '完成')], default=1),
        ),
    ]
